version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    networks:
      - uninet

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 5000 -w users.json
    ports:
      - "5000:5000"
    volumes:
      - ./src/data:/data

networks:
  uninet:
