version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - '5000:5000'
    environment:
      - NODE_ENV=development
    networks:
      - uninet

networks:
  uninet:
